## Template Information

Based on the template [Setting up an Organised Folder Structure for Research Projects by Nikola Vukovic](http://www.nikola.me/folder_structure.html) and tweaked  by [Ryan Straight](https://github.com/ryanstraight) with [APCV 302](https://uaappcomp.github.io/apcv302/) in mind, specifically, as the focus is on using R for data analysis, this template is simple enough to fit most needs and has the media structure necessary for projects within the lab.

If you'd rather not use the R-based ecosystem for writing that's present in the template, that's fine. The folder structure will still serve you well.

The actual report document being produced is an APA 6th edition document using the [`papaja`](https://github.com/crsh/papaja) package, and uses [`rfordatascience/tidytuesday`](https://github.com/rfordatascience/tidytuesday) code. You should also install `tinytex`, of course, as per the `papaja` instructions. Some demo code had been added to the script files and dummy text to the `draft.Rmd` to produce an example PDF. The `Bee Colony losses` dataset is loaded as an example. You'll notice heavy use of the `here` package, as well.

**Important**: each time you knit `draft.Rmd`, you will query GitHub. There is a limit on how often you can do this. Manually downloading the data into the folder for raw data and loading from there will get around this.

An example of how to do this is to remove the `tidytuesdayR` data loading line from `munge.R`. Instead, simply run this in the console:

```r
download.file('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/colony.csv', here::here("3-Study", "2-Content", "1-Data", "raw", "colony.csv"))
```

Then, your data load in `munge.R` would be as such and you needn't worry about loading from GitHub:

`colony <- readr::read_csv(here::here("3-Study", "2-Content", "1-Data", "raw", "colony.csv'))`


## Authors

1. Make your copy of the [contributor's template](https://docs.google.com/spreadsheets/d/1Gl0cwqN_nTsdFH9yhSvi9NypBfDCEhViGq4A3MnBrG8/copy) and complete as needed. Ensure your spreadsheet's permissions are set to `Anyone with the link can view`.
1. Place that URL in step 2 of the [tenzing](https://rollercoaster.shinyapps.io/tenzing/) Shiny app. (You can use [this spreadsheet](https://docs.google.com/spreadsheets/d/1-WmAfoW3HoHGfmeahcOrSTGxXwZpScUBajoHHrQ0Qy8/edit#gid=0) as a demonstration if you like.)
1. Choose `Show papaja YAML` in Step 3.
1. Replace the `author` and `affiliation` frontmatter in the `draft.Rmd` file with this new YAML.

## Report

The resultant publications from this project go in `4-Dissemination/2-Publications/` in subfolders for each individual publication. The `papaja` document, `draft.Rmd`, has a variety of comments and instructions within as comments. These are general suggestions that follow a generic research paper structure.

## Folder and file structure

This is the default structure for a project. It's very basic and you should feel welcome to alter it to your liking. There is another README in the `3-Study/2-Content/2-Media/` folder that explains the extensive structure there. This structure is not meant to be in chronological order, just organized.

1. Project Management
    1. Proposals
    1. Finance (notes on seeking funding, so on; copies of grant proposal)
    1. Reports (not papers; project-related reports like status)
    1. Administration (CRediT author list, publication checklist, )
1. Ethics Governance
    1. Ethics Approval (IRB, CITI certification)
    1. Forms (**blank** consent, waiver, etc forms; completed forms should be stored securely)
1. Study
    1. Input (files/docs used in the experiment itself; survey instrument, anything)
    1. Content
        1. Data (raw and tidied data)
        1. Media (video recordings, audio, screencasts, so on)
    1. Data Analysis (eda, munging scripts, transformation, etc)
    1. Outputs (tables, figures, etc)
1. Dissemination
    1. Presentations (archived)
    1. Publications (archived)
    1. Publicity (archived)
    

Note that the Dissemination folder is for *archiving* content.